name: Complete App Registration Process

on:
  push:
    branches:
      - main
  workflow_dispatch:
    # inputs:
      # secondAppName:
        # description: 'Name for the second app registration'
        # required: true
        # default: 'MySecondAppRegistration'

jobs:
  create-teams-toolkit-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install Teams Toolkit CLI
        run: npm install @microsoft/teamsapp-cli@3.0.7
        
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ vars.MSFT_SERVICE_PRINCIPAL_CLIENT_ID }}","clientSecret":"${{ secrets.MSFT_SERVICE_PRINCIPAL_CLIENT_SECRET }}","tenantId":"${{ vars.MSFT_TENANT_ID }}"}'
          allow-no-subscriptions: true
          
    #  - name: Create Teams App
     #   run: |
      #    teamsapp new --interactive false --app-name "TeamsToolkitApp" --capabilities bot --programming-language csharp
       #   cd TeamsToolkitApp
        #  teamsapp provision --env dev
         # echo "TEAMS_APP_CREATED=true" >> $GITHUB_ENV